add translation for old gas
the-hideout/tarkov-data-manager pull request #345
Opened 2023-07-06 18:31 UTC by Razzmatazzz

2023-07-06 18:36 UTC, Razzmatazzz commented
.deploy

2023-07-07 00:13 UTC, GrantBirki approved these changes

2023-07-07 08:31 UTC, Shebuka requested changes

2023-07-07 08:31 UTC, Shebuka commented on src/tarkov-data-manager/translations/ru.json
> +    "ZoneFactoryCenter": "Construction",
```suggestion
    "ZoneClearVill": "Поселок",
    "ZoneCrossRoad": "Перекресток на Западном берегу",
    "ZoneDormitory": "Общежития",
    "ZoneFactoryCenter": "Стройка",
```

2023-07-07 08:31 UTC, Shebuka commented on src/tarkov-data-manager/translations/ru.json
> +    "ZoneStartVillage": "Village",
```suggestion
    "ZoneOldAZS": "Старая заправочная станция",
    "ZoneOLI": "OLI",
    "ZoneOLIPark": "Парковочный гараж OLI",
    "ZonePort": "Пирс",
    "ZonePowerStation": "Гидроэлектростанция",
    "ZonePTOR1": "Черный рыцарь",
    "ZonePTOR2": "Белый рыцарь",
    "ZoneRailStrorage": "Здания К",
    "ZoneRoad": "Дом диких/Дорога к КПП",
    "ZoneSanatorium1": "Западное крыло",
    "ZoneSanatorium2": "Восточное крыло",
    "ZoneScavBase": "Стронгхолд",
    "ZoneScavBase2": "Северо-западный бункер диких",
    "ZoneStartVillage": "Поселок",
```

2023-07-07 13:19 UTC, Razzmatazzz commented
.deploy

2023-07-07 13:24 UTC, Shebuka approved these changes

2023-07-07 13:33 UTC, merged